@Encryptor.WebUI_HostAddress = http://localhost:5196

POST {{Encryptor.WebUI_HostAddress}}/api/Encryption/Encrypt
Accept: application/json
Content-Type: application/json

{
    "data": "Hello World"
}

###

POST {{Encryptor.WebUI_HostAddress}}/api/Encryption/Decrypt
Accept: application/json
Content-Type: application/json

{
    "data": "EX5ui/rZqhLgmUOiWFN0bHHZqVpzQxGAMPjlnLPaOSIMAQJVUocCQXb41bbNCtrZLEYaUCV6EH71dk262dTEw64ZZI0jKZgZq/cvGvaP+HrvqXx5QVb17ctDAthSn9ZDaGPOv2+Hq8UoMGonuCZnoUI5FyWC7AyllYMyEFTUxgI="
}

